### ISSUE TITLE
Coming soon page launch QA checklist

### ISSUE THREAD

**Issue by noahmanger** [18F/myra#80]
In support of Treasury's testing strategy, 18F is designing and launching a "coming soon" page for myRA. This page will actually represent the sales landing page that visitors will see when the myRA product is officially launched. Between mid October and the production launch date, 18F will perform a number of design experiments to optimize conversion of the sales landing page (i.e., the rate at which users take the call-to-action to create an account). One of the primary metrics that 18F will test against during the period of the coming soon page is a "waiting list" email submission rate.
# Coming Soon Page Launch QA
## Testing
- [x] Browser test: IE 8-11, Chrome, Firefox, Safari (current versions)
- [x] Device testing: iPhone (3.5", 4", 4.7"), Android (multiple), iPad.
- [x] Test with JS turned off
- [x] Test with CSS turned off
- [x] Stress test using Blitz.io
- [x] Server monitoring configured using New Relic
- [x] HTTPS certificate and configuration
- [x] PC / old display check
- [x] Security testing (ATO) (to be completed before full production in Dec)
- [x] Validate emails are captured in MailChimp and can be exported in a usable format
## Accessibility
- [x] WAI-ARIA roles
- [x] Keyboard navigation
- [x] Proper form markup
- [x] Color contrast check
- [x] Image alt tags
- [x] Go through 508 checklist
- [x] Validate using [this tool](http://wave.webaim.org/)
## Content
- [ ] Spell-check and grammar check
- [x] Retina quality assets (note: retina.js makes it super easy)
- [x] SEO tags
- [ ] Check all links
- [x] "Site of the USA" banner? 
- [x] Beta tag / message
- [x] Privacy policy (Treasury)
- [x] Accessibility disclaimer (Treasury)
- [x] Calculator disclaimer (Treasury)
- [x] Email capture disclaimer (Treasury)
- [x] Sitemap
- [x] Indicate links to external sites (include bumpers if necessary) (before production launch)
- [x] Warning for old browsers
- [x] Redirects
- [x] Warning of javascript is turned off
- [x] 404 error page
- [x] Favicon
- [x] Proper email and phone number to contact
- [x] Resource materials for employers
## Functionality
- [x] Hook-up capture of contact info
- [x] Form submit success messages
- [x] Schema.org semantics?
- [x] Confirm Google Analytics working
- [x] Confirm Google Webmaster working
## Optimization and Validation
- [ ] Cleanup CSS
- [x] Delete unused files
- [x] Consolidate CSS and JS requests
- [x] Lint JS
- [ ] Lint CSS
- [x] Validate HTML
- [x] Optimize images
## Social Media
- [x] Facebook metatags
- [x] Twitter metatags
- [ ] Facebook and Twitter meta images
## Other
- [x] myRA PTA
